### PR TITLE
Fix missing dependencies

### PR DESCRIPTION
**Pull request by artemnikitin**

### CODE REVIEW

**Comment by jalvz** [comment]
Hi, thanks for the PR!
If I run `dep check`, I get this:

```# Gopkg.lock is out of sync:
github.com/elastic/hey-apm/compose: in Gopkg.lock's input-imports, but neither imported nor required
github.com/elastic/hey-apm/output: in Gopkg.lock's input-imports, but neither imported nor required
github.com/elastic/hey-apm/requester: in Gopkg.lock's input-imports, but neither imported nor required
github.com/elastic/hey-apm/server: in Gopkg.lock's input-imports, but neither imported nor required
github.com/elastic/hey-apm/server/api: in Gopkg.lock's input-imports, but neither imported nor required
github.com/elastic/hey-apm/server/api/io: in Gopkg.lock's input-imports, but neither imported nor required
github.com/elastic/hey-apm/server/client: in Gopkg.lock's input-imports, but neither imported nor required
github.com/elastic/hey-apm/server/docker: in Gopkg.lock's input-imports, but neither imported nor required
github.com/elastic/hey-apm/server/strcoll: in Gopkg.lock's input-imports, but neither imported nor required
github.com/elastic/hey-apm/server/tests: in Gopkg.lock's input-imports, but neither imported nor required
github.com/elastic/hey-apm/target: in Gopkg.lock's input-imports, but neither imported nor required

# vendor is out of sync:
github.com/davecgh/go-spew: hash of vendored tree not equal to digest in Gopkg.lock
github.com/elastic/hey-apm: missing from vendor
github.com/graphaelli: unused project
github.com/mailru/easyjson: hash of vendored tree not equal to digest in Gopkg.lock
github.com/olivere/elastic: hash of vendored tree not equal to digest in Gopkg.lock
github.com/pkg/errors: hash of vendored tree not equal to digest in Gopkg.lock
github.com/pmezard/go-difflib: hash of vendored tree not equal to digest in Gopkg.lock
github.com/stretchr/testify: hash of vendored tree not equal to digest in Gopkg.lock
github.com/struCoder/pidusage: hash of vendored tree not equal to digest in Gopkg.lock
golang.org/x/net: hash of vendored tree not equal to digest in Gopkg.lock
golang.org/x/text: hash of vendored tree not equal to digest in Gopkg.lock
```

**Comment by artemnikitin** [comment]
Which version of dep are you using? 
I'm using 
```
Artems-MacBook-Pro:hey-apm artemnikitin$ dep version
dep:
 version     : v0.5.0
 build date  : 2018-08-16
 git hash    : 224a564
 go version  : go1.10.3
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false
```
and for me `dep check` doesn't produce any errors

**Comment by jalvz** [comment]
i was using an older version, updated to latest now. still confused about the internal imports. 
this is the diff i get when running `dep ensure`

```diff
diff --git a/Gopkg.lock b/Gopkg.lock
index 80e5976..16a4809 100644
--- a/Gopkg.lock
+++ b/Gopkg.lock
@@ -9,26 +9,6 @@
   revision = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
   version = "v1.1.1"
 
-[[projects]]
-  branch = "master"
-  digest = "1:d15be7dee033e6ead2ab4d56f89bac9b74911e00c285dcda25356aa039afa9b3"
-  name = "github.com/elastic/hey-apm"
-  packages = [
-    "compose",
-    "output",
-    "requester",
-    "server",
-    "server/api",
-    "server/api/io",
-    "server/client",
-    "server/docker",
-    "server/strcoll",
-    "server/tests",
-    "target",
-  ]
-  pruneopts = "NUT"
-  revision = "4ecabb3dff6fc91337b328037ffd8972860e73a2"
-
 [[projects]]
   branch = "master"
   digest = "1:853fe95bef4c5e8a70dcd405b5206b38a9ff09e9c26fef93d1d0adeaea39f9ce"
@@ -126,17 +106,6 @@
   analyzer-name = "dep"
   analyzer-version = 1
   input-imports = [
-    "github.com/elastic/hey-apm/compose",
-    "github.com/elastic/hey-apm/output",
-    "github.com/elastic/hey-apm/requester",
-    "github.com/elastic/hey-apm/server",
-    "github.com/elastic/hey-apm/server/api",
-    "github.com/elastic/hey-apm/server/api/io",
-    "github.com/elastic/hey-apm/server/client",
-    "github.com/elastic/hey-apm/server/docker",
-    "github.com/elastic/hey-apm/server/strcoll",
-    "github.com/elastic/hey-apm/server/tests",
-    "github.com/elastic/hey-apm/target",
     "github.com/olivere/elastic",
     "github.com/pkg/errors",
     "github.com/stretchr/testify/assert",
```

**Comment by artemnikitin** [comment]
> this is the diff i get when running `dep ensure`
On `master` or on my change? If on master then it's ok, because in `Gopkg.toml` there is only 1 dependency: `github.com/olivere/elastic`

**Comment by jalvz** [comment]
that diff is on your change.
`github.com/elastic/hey-apm/compose` etc belongs to the project, my question is why should be it in `Gopkg.toml`?

**Comment by artemnikitin** [comment]
Oh, sorry. I see...
Yeah, the issue was because I forked it and needed either to rewrite import paths or change `Gopkg.toml`.
I pushed changes which excluding `github.com/elastic/hey-apm/`

**Comment by artemnikitin** [comment]
Great, glad to help :)

**Pull request merged**
